version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech_challenge_fiap_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=test_user
      - DATABASE_PASSWORD=test_password
      - DATABASE_NAME=test_database
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: tech_challenge_fiap_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
